# как часто очищать папку
timeClean: 2s
# путь до папки
filePath: ./
# параметры логирования
logger:
  logLevel: DEBUG
  logFileEnable: true
  logStdoutEnable: true
  logFile: ./log.log
  rewriteLog: true